### ISSUE TITLE
audio not working on client with Safari

### ISSUE THREAD

**Issue by male-gal** [Mindgamesnl/OpenAudioMc#97] opened 2019-02-13 20:25 UTC
OpenAudioMc Version: 5

Audio started via /openaudio start, jukebox and regions aren't played on client on safari navigator (tested versions : 10 -> 12)

Connection is well established between server and client tough. Probably an issue with javascript music playing on safari.

**Comment by Mindgamesnl** [comment] 2019-02-13 20:28
Issue repoduced/confirmed on macbook.
Altough i'm not quite sure yet, it seems to be something with their implementation of the audio playing rules.

It's beginning to look like the new IE12 after all.

Planning to pick this up further on sunday.

**Comment by Mindgamesnl** [comment] 2019-02-15 09:20
Progress!

Okay, found the issue.
And it turns out, it's just _reaaalllyyyy_ stupid.

The api OpenAudioMc uses (https://github.com/Mindgamesnl/WebAudio) registers a sound as playable once the first bit is loaded. This ensures quick and snappy playback while the other parts of the song are still loading.

But as it turns out, **Safari** marks the sound as playable when, and ONLY when the COMPLETE sound has been downloaded. And even that, is really slow.

So I'll have to look into an other solution for the loading of media files on Safari.
I don't say that apple makes bad software, but they have some really stupid stuff.. There sure are great people there, but I don't know what they do all day.

**Comment by Mindgamesnl** [comment] 2019-09-23 09:44
Should be fixed, kinda forgot about it lol

**Closed by Mindgamesnl** 2019-09-23 09:44 UTC
Labels: bug
