### ISSUE TITLE
Live Stream

### ISSUE THREAD

**Issue by msburgess3200** [Mindgamesnl/OpenAudioMc#147] opened 2020-07-15 19:54 UTC
**Describe the bug**
Whenever I attempt to add a live stream radio, e.g. 
http://bravo.tss3.us:8000/minecraft.ogg
The speaker gets created however, it does not work and errors out when attempting to read the data.

**Screenshots**
https://i.imgur.com/BOVR0fd.png

**Desktop (please complete the following information):**
 - Plugin Version: 6.3.2
 - Server Version: BungeeCord, Version 1.16-R0.2
 - Web client used: client.openaudiomc.net (default)
 - Other setup details: /oa speaker http://bravo.tss3.us:8000/minecraft.ogg 15

**Additional context**
You may conduct your own test using the following stream:
http://bravo.tss3.us:8000/minecraft.ogg

I tend to use the live stream above for my server. Any help would be greatly appreciated.

Best wishes,
MikeB

**Comment by Mindgamesnl** [comment] 2020-07-15 22:08
Looked into it, here's what I found.

Piece of background information first: OpenAudioMc enforces SSL (https) when the client itself is on ssl too, this means that one of our proxy servers will forward the content (securely tunneling it, example: https://media.openaudiomc.net/proxy?apiurl=http://craftmend.com/a.mp3). This means that it downloads the file, streams it back, and then closes the connection. 3D speakers add an extra step to this by setting some headers.

The link that you are using is a live one, which is fine for all non-3D sources, but the problem is that its over http. As described, OpenAudioMc tries to proxy it, and this is where shit hits the fan. The download process fails because its an endless source so it gets timed out, resulting in the client not getting any data and shitting its pants.

You have a few options from here:
 - Accept the non ssl client and downgrade everything to HTTP (go to oa plus (`/oa plus`), settings, and change `https://` to `http://` in the client url)
or (what I recommend, if possible)
 - get a SSL certificate for your stream server (if its even yours) to properly support modern web standards.

Do note that the first workaround might break later on since browsers are tightening web security around websites that try to play audio.

I'm closing the issue now since it's technically not something on our site or a bug but feel free to ask for further support in discord (but please do so in tech talk if its server administration related or in openaudiomc-help if further questions arise from this message)

Have a wonderful day, and thank you for reaching out.

**Closed by Mindgamesnl** 2020-07-15 22:08 UTC
